service: bref-pgdump

provider:
  name: aws
  region: eu-central-1
  stage: prod
  ecr:
    images:
      arm-php-fpm-83-pgdump:
        path: .
        file: Dockerfile.fpm.prod
      arm-php-console-83-pgdump:
        path: .
        file: Dockerfile.console.prod
  environment:
    APP_KEY: ${ssm:/${self:service}/APP_KEY}
  #   BREF_BINARY_RESPONSES: "1"
  # apiGateway:
  #   binaryMediaTypes:
  #     - "*/*"

package:
  patterns:
    - "!.devcontainer/**"
    - "!.github/**"
    - "!.vscode/**"
    - "!public/vendor"
    - "!tests/**"
    - "!.editorconfig"
    - "!.env.example"
    - "!.gitattributes"
    - "!.php-cs-fixer.dist.php"
    - "!phpunit.xml"
    - "!README.md"

functions:
  web:
    architecture: arm64
    url: true
    image: arm-php-fpm-83-pgdump

  artisan:
    architecture: arm64
    image: arm-php-console-83-pgdump

plugins:
  - ./vendor/bref/bref
