service: bref-pgdump

provider:
  name: aws
  region: eu-central-1
  stage: prod
  ecr:
    images:
      php-console-83-pgdump:
        path: ./Dockerfile.prod
  environment:
    APP_KEY: ${ssm:/${self:service}/APP_KEY}
    BREF_BINARY_RESPONSES: "1"
  apiGateway:
    binaryMediaTypes:
      - "*/*"

package:
  patterns:
    - "!.devcontainer/**"
    - "!.github/**"
    - "!.vscode/**"
    - "!public/vendor"
    - "!tests/**"
    - "!.editorconfig"
    - "!.env.example"
    - "!.gitattributes"
    - "!.php-cs-fixer.dist.php"
    - "!phpunit.xml"
    - "!README.md"

functions:
  web:
    handler: public/index.php
    runtime: php-console-83-pgdump
    architecture: arm64
    url: true

plugins:
  - ./vendor/bref/bref
  # - ./vendor/bref/extra-php-extensions
