name: bref-pgdump

services:
  bref-pgdump:
    image: nginx:1.27.2-alpine-slim
    volumes:
      - ..:/var/www/bref-pgdump:cached
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - traefik.http.routers.bref-pgdump.rule=Host(`api.bref-pgdump.localhost`)
      - traefik.http.routers.bref-pgdump.tls=true

  php:
    image: cirolosapio/php-fpm:8.3-pgsql
    labels: [ traefik.enable=false ]
    working_dir: /var/www/bref-pgdump
    volumes:
      - ..:/var/www/bref-pgdump:cached
      - ~/.aws:/home/vscode/.aws:rw
      - ~/.zsh_history:/home/vscode/.zsh_history:rw
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini:ro
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

networks:
  default:
    name: bref-pgdump

